### ISSUE TITLE
0x8007007B 的另一种原因

### ISSUE THREAD

**Issue by anysoft** [YerongAI/Office-Tool-docs#1]
# `0x8007007B `的另一种原因
> 可能是更新通道错误

可以按以下步骤尝试：
1. 工具箱-->Office工具-->更改Ofiice更新通道(当前通道)-->是否检查更新-->否
2. 激活

我这边之前安装使用的 `Office 2021 企业长期版` 通道，激活的时候报`0x8007007B `,重置`Software Protection 服务` 无法解决，最后修改更新通道到`当前通道` 就可以正常激活了

**Comment by YerongAI** [comment]
看起来并没有很大的说服力，因为激活 Office 完全不依赖 Office 本身。一个例子就是可以在没有安装 Office 的情况下激活 Office 许可证。

**Comment by CMV-1** [comment]
> 看起来并没有很大的说服力，因为激活 Office 完全不依赖 Office 本身。一个例子就是可以在没有安装 Office 的情况下激活 Office 许可证。

目前也是遇到这个错误，不知道怎么解决，求助

**Comment by YerongAI** [comment]
> > 看起来并没有很大的说服力，因为激活 Office 完全不依赖 Office 本身。一个例子就是可以在没有安装 Office 的情况下激活 Office 许可证。
> 
> 目前也是遇到这个错误，不知道怎么解决，求助

[https://www.officetool.plus/zh-cn/help/activation.html#_0x8007007b](https://www.officetool.plus/zh-cn/help/activation.html#_0x8007007b)
